### ISSUE TITLE
fake_gps per server

### ISSUE THREAD

**Issue by jpmeijers** [kersing/packet_forwarder#1]
TTN wants us not to use fake_gps if a gateway does not have a GPS, as the location should be configured via the console. Other servers might still need the location in the status updates.
See: https://www.thethingsnetwork.org/docs/gateways/registration.html#start-with-configuration

Recommendation:
Add include_gps or a similar setting in the server block of the config.

**Comment by johanstokking** [comment]
In fact, the packet forwarder should get the gateway configuration on start, with the right frequency plan and location set in the Console.

cc @romeovs

**Comment by kersing** [comment]
@jpmeijers: an additional switch is not required, TTN delivery uses the ttn-gateway-connector (in ttn_transport.c) so not including the data in the status packets when fake_gps is set is sufficient.

@johanstokking: The software stack should get the correct configuration. This means the start script can take care of this using wget or something along those lines. There is no need to incorporate this into the packet forwarder.

**Comment by johan** [comment]
(Just a FYI, @kersing: @ pings the github account you reference; you'd want @johanstokking next time.)
