### ISSUE TITLE
build-pi.sh some errors

### ISSUE THREAD

**Issue by sbiermann** [kersing/packet_forwarder#11]
Hi,
it seems there are some errors in the build-pi.sh. The first error is that `apt-get -y install protobuf-compiler libprotobuf-dev libprotoc-dev automake libtool autoconf python-dev python-rpi.gpio` runs into an error because no python-rpi.gpio can be found.
Without it the next error is:
`hecking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for protobuf... no
configure: error: Package requirements (protobuf >= 2.6.0) were not met:

Requested 'protobuf >= 2.6.0' but version of Protocol Buffers is 2.4.1

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables protobuf_CFLAGS
and protobuf_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No rule to make target `protobuf-c/libprotobuf-c.la'.  Stop.
./build-pi.sh: line 80: ./libtool: No such file or directory
mkdir -p build/output/samples
`
I'm using the script to build a docker image which i can use with my ic880a-Gateway on a Pi Zero W.

Kind regards
Stefan

**Comment by kersing** [comment]
For Docker use https://github.com/jpmeijers/ttn-resin-gateway-rpi  It is a ready to use setup.
