### ISSUE TITLE
Add support for beacons

### ISSUE THREAD

**Issue by kalon33** [kersing/packet_forwarder#14]
Please add support for beacons, as discussed in this [TTN forum thread](https://www.thethingsnetwork.org/forum/t/raspberry-pi-3-ic880a-gps/7672/53) :)

**Comment by kersing** [comment]
The software supports beacons. It requires semtech protocol to be enabled (in use for at least one connection to back-end) and configuration in local_conf.json. (As well as GPS to be connected)

**Comment by kalon33** [comment]
@kersing So that's not working when connected using TTN protocol? 

----- Mail original -----

De: "Jac Kersing" <notifications@github.com> 
À: "kersing/packet_forwarder" <packet_forwarder@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Author" <author@noreply.github.com> 
Envoyé: Dimanche 21 Janvier 2018 22:22:51 
Objet: Re: [kersing/packet_forwarder] Add support for beacons (#14) 



The software supports beacons. It requires semtech protocol to be enabled (in use for at least one connection to back-end) and configuration in local_conf.json.

**Comment by johanstokking** [comment]
@kalon33 we're getting native Class B support in V3, see announcement for the webinar this Thursday afternoon CET!

**Comment by kalon33** [comment]
@johanstokking Nice! When could we expect it to be usable, both in backend with V3 and in the packet forwarder? Does it need an update in the packet forwarder or will be usable as soon as V3 is deployed?

**Comment by johanstokking** [comment]
It will need an update in the packet forwarder. V3 deployment planning is announced in the webinar this Thursday and further info at The Things Conference next week.
