### ISSUE TITLE
 ERROR: [TTN] send status failed for bridge.asia-se.thethings.network

### ISSUE THREAD

**Issue by markruys** [kersing/packet_forwarder#16]
I upgraded from 3.0.0 to 3.0.20 on a Conduit mLinux. In about 30% of the occasions I get errors like:
```
16:26:47  INFO: [TTN] bridge.asia-se.thethings.network RTT 629
16:26:49  ERROR: [TTN] send status failed for bridge.asia-se.thethings.network
16:26:49  INFO: [TTN] Reconnecting bridge.asia-se.thethings.network
16:26:52  INFO: [TTN] server "bridge.asia-se.thethings.network" connected
```
On 3.0.0 I never got this message. What can the cause of this be? Some timeout? If so, can I increase this timeout?

**Comment by kersing** [comment]
30% of what? Of status pushes?
There is no timeout involved that can be changed.

**Comment by markruys** [comment]
I noticed the upgrade from 3.0.0 to 3.0.20 left the old processing running, so I rebooted the gateway, just to be sure. Also I switched to bridge.eu.thethings.network, although the gateway is installed in Dubai (with a 3G backhaul).

Out of 80 status pushes, 10 log this message "send status failed". Also I noticed that the at the TTN console, the Last Seen sometimes shows a few minutes (should be reset each 30 seconds). And I miss uplink messages (not sure how many, this takes some more time to determine).

**Comment by kersing** [comment]
> I noticed the upgrade from 3.0.0 to 3.0.20

In the upgrade instructions on the TTN forum restarting the packet forwarder is explicitly mentioned.

We've seen issues with the EU bridge several times over the last week. Messages missing from console/app when reported sent on the gateway, gateways not updating status etc. This has been observed with both old and new MP code base and with TTN gateways which indicates it is not related to the 3.0.20 version of the software.

**Comment by kersing** [comment]
Are you still having issues? If not, please close this issue.
