### ISSUE TITLE
Enhancement: Use GPS as time reference but fake coordinates for location

### ISSUE THREAD

**Issue by Bjoerns-TB** [kersing/packet_forwarder#18]
I want to use gps for timing only. The location of my gps antenna results in a gps fix with at least 12 satellites, but with an deviation up to 100 meters and more. A can’t place the antenna at a better position, so i have to deal with this bad results.
The side affect from the incorrect location is, that my GWs location also moves in TTNMapper, resulting in hidden measurements.

So it would be great for me, making it possible to use GPS for timing, but fake coordinates for location.

Thank you very much.

**Comment by kersing** [comment]
Due to the way the code is structured this might already work if you use TTN transport and add "fake_gps": true and the "ref_altitude" etc to the configuration.

**Comment by Bjoerns-TB** [comment]
When setting fake_gps to true, the GPS module won't be initialized any more. I forked the repo, modified it and managed to get it running. For me this is working now. I don't know if this feature is intersting for others, but i don't think so.

Thank you.

**Comment by kersing** [comment]
You are right, the feature is not particular interesting for most people. Also TTN V3 back-end will ignore GPS coordinates (too many people abusing fake_gps) so it will not be required later this year.
