### ISSUE TITLE
Program killed when internet is not available

### ISSUE THREAD

**Issue by yseraf** [kersing/packet_forwarder#19]
Following the standard packet-forwarder from Semtech or the poly-packet-forwarder from TTN, when the forwarder is started and no internet connection is up on the target, it will result in a exit_failure. This is particularly the case when for example a gateway is connected to a 3/4G access point which boot at the same time.

I already modified these 2 forwarders to manage this use case and simply wait for internet to be available. 
It's cleary a matter of opinion but I prefer to manage this case directly in the packet forwarder instead of adding a script which would have to restart the packet-forwarder multiple time until the connection is available. 

I don't know your opinion about this point but if you are interested in managing it directly in your packet-forwarder, I would be pleased to discuss about it with you how we can integrate it, let me know.

**Comment by yseraf** [comment]
I agree with you but without systemd, it's not so clean... In addition, I don't think any parameter could change that since the exit_failure comes from the call to getaddrinfo with returns an error if no connection is detected. 

It's not a problem, I will integrite myself in your code but if you want to integrate it directly in your repo, let me know.

**Comment by kersing** [comment]
That call is not being used for TTN transport when initializing the connection. So the mentioned parameter should work just fine.

**Comment by kersing** [comment]
I will not change the behavior of the packet forwarder. As stated before the system should have an internet connection in place before starting the packet forwarder. TTN strongly suggests to download the most recent global_conf.json file for the region when starting the packet forwarder, this needs to be done before start of the forwarder and requires an internet connection as well.
