### ISSUE TITLE
GPSD support

### ISSUE THREAD

**Issue by jpmeijers** [kersing/packet_forwarder#2]
It would be nice to tell the packet forwarder to obtain the gps location from GPSD. In that case we can have multiple programs sharing the same gps device. Think about NTPD: it normally wants both the PPS signal, as well as the time data (via nmea, etc). If the packet forwarder has the gps tty device open, ntpd can not obtain this info.

Switching completely to GPSD is also not a good idea, because one might want a very lightweight gateway, without running the bloated gpsd service.

**Comment by kersing** [comment]
I will not implement gpsd support. The software is meant for devices where it makes no sense (imho) to run additional software that would require gpsd to run. For LoRaWAN use it makes more sense to connect PPS to the concentrator for better time stamps.

**Comment by chrissnow** [comment]
gpspipe almost solves this. it would need a few tweaks to make it work due to the way the file is opened.
