### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by dgomes** [kersing/packet_forwarder#22]
Any chance of releasing updated binaries ?

I'm only aware of those at < link removed >

**Comment by kersing** [comment]
Latest MultiTech binaries are at https://github.com/kersing/multitech-installer. Not releasing any other binaries as there is no demand.

**Comment by dgomes** [comment]
I was looking for kerlink binaries :(

**Comment by kersing** [comment]
Sorry, there has only been 1 tester for the kerlink libraries and no permanent install that I am aware of. As a result I do not create builds for the platform. (Not having hardware to test on made it difficult anyway)

**Comment by dgomes** [comment]
I have a permanent install (eui-0000024b08060086) currently running your latest binaries, but since some weeks ago the gateway loses connection to TTN after few days (although no error shows up on logs)

I will look into setting up a cross compiling environment and produce my own binaries. 

Tks for your code!

**Comment by kersing** [comment]
:+1: The old binaries have a known issue with connections disappearing on connectivity issues with the back-end. Those have been solved for some time now. I could try to find the build script I used to cross compile if that helps. (Not promising I can find it as I was using a VM that developed disk errors at some point)

**Comment by dgomes** [comment]
That would be fantastic! I could really use that build script ;)

**Comment by kersing** [comment]
At the previously mentioned site there is a file kerlink.tgz with the scripts used for cross compiling. Included is a build based on the latest sources.

**Comment by dgomes** [comment]
Tks so much!
