### ISSUE TITLE
Cant connect to a private tti instance using mp_pkt_fwd

### ISSUE THREAD

**Issue by Maoie86** [kersing/packet_forwarder#23]
Greetings!

We subscribed to a private instance of tti and we are having problems connecting to it. I edited run.py to get the gateway details to get it from our own instance. The gateway has no problem with that as it can get the freq, gateway key, gps etec. But the gateway can't connect to the private instance.

I messaged jpmeijers and this is what he said: 

>  I normally use the UDP/Semtech protocol to connect to private TTI instances. Normally what 
>  happens is that private instances use different ports for the different services. As far as I know 
>  MP-packet-forwarder can't be told to use a different port for the TTN connector (mqtt/protobuf) 
> protocol. So the port it is trying to connect to is most likely the incorrect one for you server. 

I'd like to confirm if there is no way of changing the port mp_pkt_fwd tries to connect to the private tti instance?  Can't the codes be changed to accomodate changing the ports? 

Thanks!

**Comment by Maoie86** [comment]
I've tried addding :port to the end of the address and it still won't connect.

**Comment by kersing** [comment]
@jpmeijers is wrong, specifying the port has been implemented over a year ago.

The port can be specified by adding it to the end of the address, for instance:
my.privateinstance.local:1882
Make sure to specify the **un**encrypted mqtt port.

BTW, for questions please use the TTN forum, not this issue tracker.

**Comment by Maoie86** [comment]
Thanks.  Will post next question to the TTN forum.

**Comment by Maoie86** [comment]
just to let you know. jpmeijers modified his script to accomodate different ports. Am now able to connect to our ttn private instance. :) thanks!

**Comment by kersing** [comment]
Glad this has been resolved.
