### ISSUE TITLE
Connection lost? 

### ISSUE THREAD

**Issue by tho-wa** [kersing/packet_forwarder#24]
Is it possible that the multi packet forwarder somehow loses connection to router and does not re-establish the connection without restarting the gateway?
I have “Last Seen 29 minutes ago” in gateway status, also in the Application that have nodes near to this gateway, but when I check the last gateway output there is no error and it says connected:’

06.09.18 21:19:34 (+0200) main ##### 2018-09-06 19:19:34 GMT #####
06.09.18 21:19:34 (+0200) main ### [UPSTREAM] ###
06.09.18 21:19:34 (+0200) main # RF packets received by concentrator: 0
06.09.18 21:19:34 (+0200) main # CRC_OK: 0.00%, CRC_FAIL: 0.00%, NO_CRC: 0.00%
06.09.18 21:19:34 (+0200) main # RF packets forwarded: 0 (0 bytes)
06.09.18 21:19:34 (+0200) main # PUSH_DATA datagrams sent: 0 (0 bytes)
06.09.18 21:19:34 (+0200) main # PUSH_DATA acknowledged: 0.00%
06.09.18 21:19:34 (+0200) main ### [DOWNSTREAM] ###
06.09.18 21:19:34 (+0200) main # PULL_DATA sent: 0 (0.00% acknowledged)
06.09.18 21:19:34 (+0200) main # PULL_RESP(onse) datagrams received: 0 (0 bytes)
06.09.18 21:19:34 (+0200) main # RF packets sent to concentrator: 0 (0 bytes)
06.09.18 21:19:34 (+0200) main # TX errors: 0
06.09.18 21:19:34 (+0200) main ### BEACON IS DISABLED!
06.09.18 21:19:34 (+0200) main ### [JIT] ###
06.09.18 21:19:34 (+0200) main # INFO: JIT queue contains 0 packets.
06.09.18 21:19:34 (+0200) main # INFO: JIT queue contains 0 beacons.
06.09.18 21:19:34 (+0200) main ### [GPS] ###
06.09.18 21:19:34 (+0200) main # No time keeping possible due to fake gps.
06.09.18 21:19:34 (+0200) main # Manual GPS coordinates: latitude 50.69847, longitude 13.00944, altitude 447 m
06.09.18 21:19:34 (+0200) main ### [PERFORMANCE] ###
06.09.18 21:19:34 (+0200) main # Upstream radio packet quality: 0.00%.
06.09.18 21:19:34 (+0200) main ### [ CONNECTIONS ] ###
06.09.18 21:19:34 (+0200) main # ttn.thingsconnected.net: Connected
06.09.18 21:19:34 (+0200) main # Semtech status report send.
06.09.18 21:19:34 (+0200) main ##### END #####
06.09.18 21:19:34 (+0200) main 19:19:34 INFO: [TTN] ttn.thingsconnected.net RTT33
06.09.18 21:19:34 (+0200) main 19:19:34 INFO: [TTN] send status success for ttn.thingsconnected.net
06.09.18 21:19:38 (+0200) main 19:19:38 INFO: [up] TTN lora packet send to server “ttn.thingsconnected.net”
06.09.18 21:20:04 (+0200) main

**Comment by kersing** [comment]
If the connection is lost it will log an error and (attempt) to reconnect. Every status update shows the RTT time, this is a turn around time which requires the back-end to send an MQTT ACK for data received.
The behavior observed points to a disconnect between the back-end components, not an issue with the packet forwarder connection to the back-end.

In the future please use the TTN forum for questions and these issues for (confirmed) bugs.
