### ISSUE TITLE
No include file  "connector.h"

### ISSUE THREAD

**Issue by dkalog** [kersing/packet_forwarder#26]
referenced in https://github.com/kersing/packet_forwarder/blob/master/mp_pkt_fwd/src/mp_pkt_fwd.c line:72 in 
dir https://github.com/kersing/packet_forwarder/tree/master/mp_pkt_fwd/inc

**Comment by kersing** [comment]
Please make sure to install the required dependencies (in this case ttn-gateway-connector) before building.
