### ISSUE TITLE
wiringPi issue

### ISSUE THREAD

**Issue by fernandobarreto** [kersing/packet_forwarder#29]
I think the wiringPi is deprecated (http://wiringpi.com/wiringpi-deprecated/) , is there a fix for its dependency in build-pi.sh ?

**Comment by kersing** [comment]
There is no real fix required. To build you can just remove the wiringPi references from the build script. The packet forwarder code does **not** include the wiringpi code not does it depend on it while building.

For the software to run you need something to reset the concentrator card. Anything that allows you to toggle the reset pin will do. Feel free to suggest something.

**Comment by saynono** [comment]
You can install wiringPi with ```sudo apt-get install wiringpi```
See [http://wiringpi.com/download-and-install/](http://wiringpi.com/download-and-install/)
