### ISSUE TITLE
packet forwarder not starting

### ISSUE THREAD

**Issue by cipy** [kersing/packet_forwarder#34]
-- Logs begin at Thu 2020-10-29 22:25:46 EET, end at Thu 2020-10-29 22:31:18 EET. --
Oct 29 22:26:02 piAir systemd[1]: Starting IOT LoRa Gateway Packet Forwarder...
Oct 29 22:26:04 piAir iot-lora-gateway-reset.sh[538]: PHP Notice:  Undefined index: lbt_cfg in /var/www/iotloragateway/html/updatePacketfwd.php on line 159
Oct 29 22:26:04 piAir iot-lora-gateway-reset.sh[538]: 
Oct 29 22:26:04 piAir iot-lora-gateway-reset.sh[538]:

**Comment by kersing** [comment]
There are no php scripts part of this packet forwarder so this is not the right place for this issue.
