### ISSUE TITLE
Cross-compilation for Kerlink iStation

### ISSUE THREAD

**Issue by qbaj** [kersing/packet_forwarder#36]
Hi,
i'd like to use the source in cross-comilation for my Kerlink iStation. But no success. 
Could you describe step by step how I can do it, please?

Kerlink iStation with KerOS
root@klk-wiis-0508DE:~ # uname -a
Linux klk-wiis-0508DE 4.14.9-klk #1 SMP Mon Aug 3 15:12:22 CEST 2020 armv7l GNU/Linux
root@klk-wiis-0508DE:~ # opkg list-installed
keros - 4.3.3-0-g993efce1
root@klk-wiis-0508DE:~ # cat /etc/version
4.3.3_20200803132042

**Comment by kersing** [comment]
Sorry, sources are provided as is. I do not have the time to provide support for all kinds of platforms.
