### ISSUE TITLE
fatal error: connector.h: No such file or directory

### ISSUE THREAD

**Issue by MarceloLP1** [kersing/packet_forwarder#7]
Hi.
I'm compiling your new "packet forward", and when I tried to run make, there are a lost file !!. 
I controlled that in the folder :packet_forwarder/mp_pkt_fwd/inc/connector.h and
packet_forwarder/mp_pkt_fwd/src/connector.c, does not exist!

Where can I found / download these files ?

log:
src/mp_pkt_fwd.c:72:23: fatal error: connector.h: No such file or directory

MarceloLP.

**Comment by kersing** [comment]
These files are part of the ttn-gateway-connector repository. See build.txt for all the repositories required to build from source.
